In [20]:
import pandas as pd

# data = pd.read_csv('rulesm_raw/rulesm_part_2.csv')
data = pd.read_csv('rulesm_test - english_dataset.csv')

In [21]:
data

,url,paragraph_1,paragraph_2,span_1,span_2,Label,Anchor_span,subset,Unnamed: 8,Unnamed: 9
0,https://www.govinfo.gov/app/collection/uscode/...,Committee on Education and the Workforce of Ho...,Committee on Education and the Workforce of Ho...,NaN,Committee on Education and Labor of House of R...,Addition,Committee on Education and the Workforce of Ho...,"TITLE 2, CHAPTER 2 - ORGANIZATION OF CONGRESS",NaN,NaN
1,https://www.govinfo.gov/app/collection/uscode/...,‘‘(1) the Committee on District of Columbia of...,‘‘(1) the Committee on District of Columbia of...,Reform,Accountability,Contradiction,NaN,"TITLE 2, CHAPTER 2 - ORGANIZATION OF CONGRESS",NaN,NaN
2,https://www.govinfo.gov/app/collection/uscode/...,Committee on Oversight and Government Reform o...,Committee on Oversight and Government Reform o...,NaN,Committee on Oversight and Reform of House of ...,Addition,Committee on Oversight and Government Reform o...,"TITLE 2, CHAPTER 2 - ORGANIZATION OF CONGRESS",NaN,NaN
3,NaN,F. Those functions of the Office of Management...,F. Those functions of the Office of Management...,section 7 of the Federal Advisory Committee Ac...,5 U.S.C. 1006,Contradiction,NaN,"TITLE 3, CHAPTER 2",NaN,2020-2024
4,NaN,"Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...","Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...",NaN,formerly,Addition,set out as a note,"TITLE 3, CHAPTER 3",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
74,NaN,When applicable this table shall indicate sepa...,"When applicable, that table shall also indicat...",NaN,also,Addition,table shall,NaN,NaN,NaN
75,NaN,When applicable this table shall indicate sepa...,"When applicable, that table shall also indicat...",in application of,pursuant to,Equivalent,NaN,NaN,NaN,NaN
76,NaN,The scheme of authorisations for vine planting...,The scheme of authorisations for vine planting...,to 31 December 2045,NaN,Addition,NaN,NaN,NaN,NaN
77,NaN,The scheme of authorisations for vine planting...,The scheme of authorisations for vine planting...,two mid-term reviews,a review,Contradiction,NaN,NaN,NaN,NaN
78,NaN,The scheme of authorisations for vine planting...,The scheme of authorisations for vine planting...,2040,every ten years thereafter,Contradiction,NaN,NaN,NaN,NaN

In [22]:
import pandas as pd

data['span_1'] = data['span_1'].fillna("")
data['span_2'] = data['span_2'].fillna("")

group_cols = ["paragraph_1", "paragraph_2"]
list_cols  = ["span_1", "span_2", "Label", "Anchor_span"]

data = data[data['Label'].isin(['Contradiction', 'Addition'])]
# data['Anchor_span'] = data['итоговый anchor'].fillna("")

result = (
    data.groupby(group_cols, as_index=False)
      .agg({col: list for col in list_cols})
)

In [23]:
result

,paragraph_1,paragraph_2,span_1,span_2,Label,Anchor_span
0,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,"[3,237,000]","[10,000,000]",[Contradiction],[nan]
1,"(A) subject to subparagraph (B), means a perso...","(A) subject to subparagraph (B), means a perso...",[or operating real property or activities inci...,"[single asset real estate, , less than 50 perc...","[Contradiction, Addition, Contradiction]","[nan, that has aggregate noncontingent liquida..."
2,(B) does not include any member of a group of ...,(B) does not include any member of a group of ...,[],[under this title],[Addition],[debtors]
3,"(B) who is appointed to an advisory committee,...","(B) who is appointed to an advisory committee,...","[3(2), the Federal Advisory Committee Act]","[1001, title 5]","[Contradiction, Contradiction]","[nan, nan]"
4,An amount of EUR 11 327 310 073 in current pri...,An amount of EUR 14 227 310 073 in current pri...,[11 327],[14 227],[Contradiction],[nan]
5,An operator that is a natural person or a micr...,An operator that is a natural person or a micr...,[],[downstream],[Addition],[operator]
6,By making available the due diligence statemen...,By making the due diligence statement availabl...,[],"[or, in the case of micro or small primary ope...",[Addition],[By making the due diligence statement availab...
7,By the authority vested in me as President by ...,By the authority vested in me as President by ...,[to assist faith-based and other organizations...,[in order to better serve people in need throu...,"[Contradiction, Contradiction]","[nan, nan]"
8,By way of derogation from the first subparagra...,By way of derogation from the first subparagra...,"[and, if duly justified,, ]","[, and commitments to convert to or maintain o...","[Addition, Addition]",[commitments for agricultural practices benefi...
9,Committee on Education and the Workforce of Ho...,Committee on Education and the Workforce of Ho...,[],[Committee on Education and Labor of House of ...,[Addition],[Committee on Education and the Workforce of H...
10,Committee on Oversight and Government Reform o...,Committee on Oversight and Government Reform o...,[],[Committee on Oversight and Reform of House of...,[Addition],[Committee on Oversight and Government Reform ...
11,Each Member State concerned shall submit a cor...,Each Member State concerned shall submit a not...,[corresponding request for amendment of its CA...,[notification in accordance with Article 119(9...,"[Contradiction, Addition, Addition]","[nan, subparagraph, by 31 March of the year pr..."
12,Each Vice-President-elect shall be entitled to...,Each apparent successful candidate for the off...,"[, Vice-President-elect]",[apparent successful candidate for the office ...,"[Addition, Contradiction]","[Each, nan]"
13,"Every six months, each implementing partner sh...","Once a year, each implementing partner shall s...",[Every six months],[Once a year],[Contradiction],[nan]
14,"Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...","Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...","[, 14, the Federal Advisory Committee Act in t...","[formerly, 1013, ]","[Addition, Contradiction, Addition]","[set out as a note, nan, section 14]"
15,F. Those functions of the Office of Management...,F. Those functions of the Office of Management...,[section 7 of the Federal Advisory Committee A...,[5 U.S.C. 1006],[Contradiction],[nan]
16,For commitments referred to in the first subpa...,For commitments referred to in the first subpa...,"[new, for a maximum of 24 months from the date...","[, ]","[Addition, Addition]","[requirements, support may be granted]"
17,"In order to be covered by the EU guarantee, th...",In order to be covered by the EU guarantee or ...,"[, points (a) and (b) of the first subparagraph]","[or the InvestEU financial instrument, the fir...","[Addition, Contradiction]","[In order to be covered by the EU guarantee, nan]"
18,"In such cases, the operator or trader shall re...","In such cases, the operator shall retain respo...",[or trader],[],[Addition],[the operator]
19,Member States shall notify the Commission and ...,Member States shall notify the Commission and ...,"[by 30 April of each year, of the number and l...",[of the demarcated areas immediately after the...,"[Contradiction, Addition]","[nan, nan]"
20,Nothing in this chapter shall be construed to ...,Nothing in this chapter shall be construed to ...,[North American Free Trade Agreement],[USMCA (as defined in section 4502 of title 19)],[Contradiction],[nan]
21,Operators or traders may mandate an authorised...,Operators may mandate an authorised representa...,"[or traders, ]","[, or to submit a simplified declaration pursu...","[Addition, Addition]","[Operators, Operators may mandate]"
22,Operators shall communicate to operators and t...,Operators shall communicate to downstream oper...,"[, all information necessary to demonstrate th...","[downstream, the reference numbers of the, sta...","[Addition, Contradiction, Contradiction]","[operators, nan, nan]"
23,Operators that obtain or are made aware of rel...,Operators that obtain or are made aware of rel...,[],[downstream operators and],[Addition],[nan]
24,Prior to placing relevant products on the mark...,Prior to placing relevant products on the mark...,[supplied by each particular supplier.],[],[Addition],[products]
25,SME traders shall collect and keep the followi...,Downstream operators and traders shall collect...,"[SME, , ]","[Downstream operators and, place or, or export]","[Contradiction, Addition, Addition]","[nan, they intend to, they intend to]"
26,The annual payment for each farmer shall not e...,The annual payment for each farmer under parag...,"[, 1 250]","[under paragraph 1, 3 000]","[Addition, Contradiction]","[The annual payment, nan]"
27,The checks on SME traders shall include the ex...,The checks on downstream operators and traders...,[SME],[downstream operators and],[Contradiction],[nan]
28,The checks on SME traders shall include the ex...,The checks on downstream operators and traders...,[],"[(1),]",[Addition],[Article 5]
29,The checks on operators and non-SME traders sh...,The checks on operators shall include:,[and non-SME traders],[],[Addition],[The cheks on]
30,The multiannual survey programmes shall be for...,The multiannual survey programmes shall be est...,"[, seven]","[established, 10]","[Addition, Contradiction]","[The multiannual survey programmes shall be, nan]"
31,The scheme of authorisations for vine planting...,The scheme of authorisations for vine planting...,"[to 31 December 2045, two mid-term reviews, 2040]","[, a review, every ten years thereafter]","[Addition, Contradiction, Contradiction]","[nan, nan, nan]"
32,The support shall take the form of a lump sum ...,The support shall take the form of a lump sum ...,"[30 June 2021, 31 December 2020]","[31 December 2021, 30 June 2021]","[Contradiction, Contradiction]","[nan, nan]"
33,When applicable this table shall indicate sepa...,"When applicable, that table shall also indicat...",[],[also],[Addition],[table shall]
34,investments in tangible and intangible assets ...,investments in tangible assets and intangible ...,"[, ]","[assets, including marketing through wine tour...","[Addition, Addition]","[investments in, marketing structures and tools]"
35,"the Member State strategy, consisting of the f...","the Member State strategy, consisting of the t...",[financial products and their minimum],"[type of financing, the target]",[Contradiction],[nan]
36,the performance reporting on output indicators...,the performance reporting on output indicators...,[for the purposes of the annual performance cl...,[],[Addition],[the performance reporting on output indicators]
37,they are covered by a due diligence statement.,they are covered by a due diligence statement ...,[],"[or a simplified declaration, as required by t...",[Addition],[they are covered by]
38,"varietal conversions, also by means of graftin...","varietal conversions, also by means of graftin...","[the, ]","[, increasing the climate resilience of vines,]","[Addition, Addition]","[quality, for reasons of]"
39,‘authorised representative’ means any natural ...,‘authorised representative’ means any natural ...,"[or from a trader, or the trader's]","[, ]","[Addition, Addition]","[a written mandate from an operator, the opera..."
40,‘compartment’ means a part of the EU guarantee...,‘compartment’ means a part of the support prov...,[EU guarantee],[support provided under the InvestEU Fund],[Contradiction],[nan]
41,‘contribution agreement’ means a legal instrum...,‘contribution agreement’ means a legal instrum...,"[of the EU guarantee, ]","[for the implementation of the contribution, a...","[Contradiction, Addition]","[nan, Articles]"
42,‘‘(1) the Committee on District of Columbia of...,‘‘(1) the Committee on District of Columbia of...,[Reform],[Accountability],[Contradiction],[nan]
43,‘‘(3) Payment of expenses for the procurement ...,‘‘(3) Payment of expenses for the procurement ...,[President-elect or Vice-President-elect],[apparent successful candidate],[Contradiction],[nan]

In [24]:
pd.options.display.max_colwidth = 50

In [25]:
import re
from difflib import SequenceMatcher

TOKEN_RE = re.compile(r"\w+|[^\w\s]", re.UNICODE)

def tokenize_with_offsets(text: str):
    # returns list of (tok, start, end)
    return [(m.group(0), m.start(), m.end()) for m in TOKEN_RE.finditer(text)]

PRESERVE = set(list("()[]{}«»\"'„“”–—-"))

def norm_tok(tok: str) -> str:
    t = tok.strip()
    if t in PRESERVE:
        return t
    return re.sub(r"\W+", "", t.lower(), flags=re.UNICODE)
def extend_right_closing_punct(text: str, e: int) -> int:
    # съедаем пробелы + закрывающую пунктуацию, но стопаемся перед буквой/цифрой
    while e < len(text):
        ch = text[e]
        if ch.isspace():
            e += 1
            continue
        if ch in ")]}»\"'”":
            e += 1
            continue
        break
    return e



def find_all_occurrences(text: str, span: str):
    # более устойчиво к пробелам: " " -> "\s+"
    # если надо игнорировать пунктуацию — лучше искать по токенам (см. ниже)
    if not span or not span.strip():
        return []
    pat = re.escape(span.strip())
    pat = re.sub(r"\\\s+", r"\\s+", pat)  # пробелы в span -> \s+
    return [(m.start(), m.end()) for m in re.finditer(pat, text, flags=re.UNICODE)]

def merge_intervals(intervals):
    intervals = sorted(intervals)
    merged = []
    for s, e in intervals:
        if not merged or s > merged[-1][1]:
            merged.append([s, e])
        else:
            merged[-1][1] = max(merged[-1][1], e)
    return [(a, b) for a, b in merged]

def subtract_intervals(interval, holes):
    # interval: (s,e), holes: list of (hs,he) merged, return list of остатки
    s, e = interval
    out = []
    cur = s
    for hs, he in holes:
        if he <= cur:
            continue
        if hs >= e:
            break
        if hs > cur:
            out.append((cur, min(hs, e)))
        cur = max(cur, he)
        if cur >= e:
            break
    if cur < e:
        out.append((cur, e))
    return out

def protected_ranges(text, spans):
    # пытаемся найти все точные/почти точные вхождения и объединить
    occ = []
    for sp in spans:
        occ.extend(find_all_occurrences(text, sp))
    return merge_intervals(occ)

def extract_equivalents(par1, par2, spans1, spans2, min_chars=30):
    t1 = tokenize_with_offsets(par1)
    t2 = tokenize_with_offsets(par2)

    n1 = [norm_tok(tok) for tok,_,_ in t1]
    n2 = [norm_tok(tok) for tok,_,_ in t2]

    # убираем пустые норм-токены (пунктуацию), но сохраняем маппинг индексов
    idx1 = [i for i, x in enumerate(n1) if x]
    idx2 = [j for j, x in enumerate(n2) if x]
    n1c = [n1[i] for i in idx1]
    n2c = [n2[j] for j in idx2]

    sm = SequenceMatcher(None, n1c, n2c, autojunk=False)

    prot1 = protected_ranges(par1, spans1)
    prot2 = protected_ranges(par2, spans2)

    eq1, eq2 = [], []
    for i1, j1, size in sm.get_matching_blocks():
        if size == 0:
            continue

        # границы блока в "очищенных" токенах -> в исходных токенах -> в char offsets
        a1 = idx1[i1]
        b1 = idx1[i1 + size - 1]
        a2 = idx2[j1]
        b2 = idx2[j1 + size - 1]

        s1 = t1[a1][1]
        e1 = t1[b1][2]
        s2 = t2[a2][1]
        e2 = t2[b2][2]

        e1 = extend_right_closing_punct(par1, e1)
        e2 = extend_right_closing_punct(par2, e2)

        # вычесть protected
        parts1 = subtract_intervals((s1, e1), prot1)
        parts2 = subtract_intervals((s2, e2), prot2)

        # обычно parts1 и parts2 совпадают по количеству, но не всегда.
        # берем попарно по порядку (можно усложнить матчингом по длине)
        k = min(len(parts1), len(parts2))
        for p in range(k):
            ss1, ee1 = parts1[p]
            ss2, ee2 = parts2[p]
            if (ee1 - ss1) >= min_chars and (ee2 - ss2) >= min_chars:
                eq1.append((ss1, ee1, par1[ss1:ee1]))
                eq2.append((ss2, ee2, par2[ss2:ee2]))

    return eq1, eq2

In [26]:
import re
import ast
import pandas as pd

# --- helpers ---

def ensure_list(x):
    """span columns sometimes are already lists, sometimes strings like "['a','b']"."""
    if isinstance(x, list):
        return x
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return []
    if isinstance(x, str):
        s = x.strip()
        if not s:
            return []
        # try parse python-list-like string
        if s.startswith("[") and s.endswith("]"):
            try:
                v = ast.literal_eval(s)
                return v if isinstance(v, list) else [v]
            except Exception:
                return [x]
        return [x]
    # fallback
    try:
        return list(x)
    except Exception:
        return [x]

_ws = re.compile(r"\s+", flags=re.UNICODE)

def norm_key(a: str, b: str) -> str:
    a_n = _ws.sub(" ", (a or "").strip().lower())
    b_n = _ws.sub(" ", (b or "").strip().lower())
    return a_n + "||" + b_n


def add_equivalents_row(row, *, min_chars=30):
    spans1 = ensure_list(row["span_1"])
    spans2 = ensure_list(row["span_2"])
    labels = ensure_list(row["Label"])

    eq1, eq2 = extract_equivalents(
        row["paragraph_1"],
        row["paragraph_2"],
        spans1,
        spans2,
        min_chars=min_chars,
    )

    # extract texts
    cand_pairs = [(t1, t2) for (_, _, t1), (_, _, t2) in zip(eq1, eq2)]

    # dedupe (pairwise) + drop empty/too-short after strip
    seen = set()
    pairs = []
    for a, b in cand_pairs:
        if not a or not b:
            continue
        a_s, b_s = a.strip(), b.strip()
        if len(a_s) < min_chars or len(b_s) < min_chars:
            continue
        k = norm_key(a_s, b_s)
        if k in seen:
            continue
        seen.add(k)
        pairs.append((a_s, b_s))

    # extend
    span_1_ext = spans1 + [a for a, _ in pairs]
    span_2_ext = spans2 + [b for _, b in pairs]
    label_ext  = labels + ["Equivalent"] * len(pairs)

    return pd.Series(
        {
            "span_1_ext": span_1_ext,
            "span_2_ext": span_2_ext,
            "Label_ext": label_ext,
            "n_equivalent_added": len(pairs),
        }
    )


# --- run on whole dataframe ---
out = result.apply(add_equivalents_row, axis=1)

result = pd.concat([result, out], axis=1)

# quick sanity checks
print(result["n_equivalent_added"].describe())
print(result["n_equivalent_added"].value_counts().head(20))

count    44.000000
mean      1.772727
std       0.803007
min       0.000000
25%       1.000000
50%       2.000000
75%       2.000000
max       4.000000
Name: n_equivalent_added, dtype: float64
n_equivalent_added
2    20
1    16
3     6
4     1
0     1
Name: count, dtype: int64

In [27]:
result

,paragraph_1,paragraph_2,span_1,span_2,Label,Anchor_span,span_1_ext,span_2_ext,Label_ext,n_equivalent_added
0,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,"[3,237,000]","[10,000,000]",[Contradiction],[nan],"[3,237,000, (A) individual or individual and s...","[10,000,000, (A) individual or individual and ...","[Contradiction, Equivalent, Equivalent]",2
1,"(A) subject to subparagraph (B), means a perso...","(A) subject to subparagraph (B), means a perso...",[or operating real property or activities inci...,"[single asset real estate, , less than 50 perc...","[Contradiction, Addition, Contradiction]","[nan, that has aggregate noncontingent liquida...",[or operating real property or activities inci...,"[single asset real estate, , less than 50 perc...","[Contradiction, Addition, Contradiction, Equiv...",2
2,(B) does not include any member of a group of ...,(B) does not include any member of a group of ...,[],[under this title],[Addition],[debtors],"[, (B) does not include any member of a group ...","[under this title, (B) does not include any me...","[Addition, Equivalent, Equivalent]",2
3,"(B) who is appointed to an advisory committee,...","(B) who is appointed to an advisory committee,...","[3(2), the Federal Advisory Committee Act]","[1001, title 5]","[Contradiction, Contradiction]","[nan, nan]","[3(2), the Federal Advisory Committee Act, (B)...","[1001, title 5, (B) who is appointed to an adv...","[Contradiction, Contradiction, Equivalent]",1
4,An amount of EUR 11 327 310 073 in current pri...,An amount of EUR 14 227 310 073 in current pri...,[11 327],[14 227],[Contradiction],[nan],"[11 327, 310 073 in current prices of the amou...","[14 227, 310 073 in current prices of the amou...","[Contradiction, Equivalent, Equivalent]",2
5,An operator that is a natural person or a micr...,An operator that is a natural person or a micr...,[],[downstream],[Addition],[operator],"[, An operator that is a natural person or a m...","[downstream, An operator that is a natural per...","[Addition, Equivalent, Equivalent]",2
6,By making available the due diligence statemen...,By making the due diligence statement availabl...,[],"[or, in the case of micro or small primary ope...",[Addition],[By making the due diligence statement availab...,"[, the operator shall assume responsibility fo...","[or, in the case of micro or small primary ope...","[Addition, Equivalent]",1
7,By the authority vested in me as President by ...,By the authority vested in me as President by ...,[to assist faith-based and other organizations...,[in order to better serve people in need throu...,"[Contradiction, Contradiction]","[nan, nan]",[to assist faith-based and other organizations...,[in order to better serve people in need throu...,"[Contradiction, Contradiction, Equivalent]",1
8,By way of derogation from the first subparagra...,By way of derogation from the first subparagra...,"[and, if duly justified,, ]","[, and commitments to convert to or maintain o...","[Addition, Addition]",[commitments for agricultural practices benefi...,"[and, if duly justified,, , By way of derogati...","[, and commitments to convert to or maintain o...","[Addition, Addition, Equivalent, Equivalent, E...",4
9,Committee on Education and the Workforce of Ho...,Committee on Education and the Workforce of Ho...,[],[Committee on Education and Labor of House of ...,[Addition],[Committee on Education and the Workforce of H...,"[, Committee on Education and the Workforce of...",[Committee on Education and Labor of House of ...,"[Addition, Equivalent]",1
10,Committee on Oversight and Government Reform o...,Committee on Oversight and Government Reform o...,[],[Committee on Oversight and Reform of House of...,[Addition],[Committee on Oversight and Government Reform ...,"[, Committee on Oversight and Government Refor...",[Committee on Oversight and Reform of House of...,"[Addition, Equivalent]",1
11,Each Member State concerned shall submit a cor...,Each Member State concerned shall submit a not...,[corresponding request for amendment of its CA...,[notification in accordance with Article 119(9...,"[Contradiction, Addition, Addition]","[nan, subparagraph, by 31 March of the year pr...",[corresponding request for amendment of its CA...,[notification in accordance with Article 119(9...,"[Contradiction, Addition, Addition, Equivalent...",3
12,Each Vice-President-elect shall be entitled to...,Each apparent successful candidate for the off...,"[, Vice-President-elect]",[apparent successful candidate for the office ...,"[Addition, Contradiction]","[Each, nan]","[, Vice-President-elect, shall be entitled to ...",[apparent successful candidate for the office ...,"[Addition, Contradiction, Equivalent]",1
13,"Every six months, each implementing partner sh...","Once a year, each implementing partner shall s...",[Every six months],[Once a year],[Contradiction],[nan],"[Every six months, each implementing partner s...","[Once a year, each implementing partner shall ...","[Contradiction, Equivalent]",1
14,"Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...","Ex. Ord. No. 13283, Jan. 21, 2003, 68 F.R. 337...","[, 14, the Federal Advisory Committee Act in t...","[formerly, 1013, ]","[Addition, Contradiction, Addition]","[set out as a note, nan, section 14]","[, 14, the Federal Advisory Committee Act in t...","[formerly, 1013, , Ex. Ord. No. 13283, Jan. 21...","[Addition, Contradiction, Addition, Equivalent...",3
15,F. Those functions of the Office of Management...,F. Those functions of the Office of Management...,[section 7 of the Federal Advisory Committee A...,[5 U.S.C. 1006],[Contradiction],[nan],[section 7 of the Federal Advisory Committee A...,"[5 U.S.C. 1006, F. Those functions of the Offi...","[Contradiction, Equivalent, Equivalent]",2
16,For commitments referred to in the first subpa...,For commitments referred to in the first subpa...,"[new, for a maximum of 24 months from the date...","[, ]","[Addition, Addition]","[requirements, support may be granted]","[new, for a maximum of 24 months from the date...","[, , For commitments referred to in the first ...","[Addition, Addition, Equivalent, Equivalent, E...",3
17,"In order to be covered by the EU guarantee, th...",In order to be covered by the EU guarantee or ...,"[, points (a) and (b) of the first subparagraph]","[or the InvestEU financial instrument, the fir...","[Addition, Contradiction]","[In order to be covered by the EU guarantee, nan]","[, points (a) and (b) of the first subparagrap...","[or the InvestEU financial instrument, the fir...","[Addition, Contradiction, Equivalent, Equivalent]",2
18,"In such cases, the operator or trader shall re...","In such cases, the operator shall retain respo...",[or trader],[],[Addition],[the operator],"[or trader, shall retain responsibility for th...","[, shall retain responsibility for the complia...","[Addition, Equivalent]",1
19,Member States shall notify the Commission and ...,Member States shall notify the Commission and ...,"[by 30 April of each year, of the number and l...",[of the demarcated areas immediately after the...,"[Contradiction, Addition]","[nan, nan]","[by 30 April of each year, of the number and l...",[of the demarcated areas immediately after the...,"[Contradiction, Addition, Equivalent, Equivalent]",2
20,Nothing in this chapter shall be construed to ...,Nothing in this chapter shall be construed to ...,[North American Free Trade Agreement],[USMCA (as defined in section 4502 of title 19)],[Contradiction],[nan],"[North American Free Trade Agreement, Nothing ...",[USMCA (as defined in section 4502 of title 19...,"[Contradiction, Equivalent, Equivalent]",2
21,Operators or traders may mandate an authorised...,Operators may mandate an authorised representa...,"[or traders, ]","[, or to submit a simplified declaration pursu...","[Addition, Addition]","[Operators, Operators may mandate]","[or traders, , may mandate an authorised repre...","[, or to submit a simplified declaration pursu...","[Addition, Addition, Equivalent]",1
22,Operators shall communicate to operators and t...,Operators shall communicate to downstream oper...,"[, all information necessary to demonstrate th...","[downstream, the reference numbers of the, sta...","[Addition, Contradiction, Contradiction]","[operators, nan, nan]","[, all information necessary to demonstrate th...","[downstream, the reference numbers of the, sta...","[Addition, Contradiction, Contradiction, Equiv...",2
23,Operators that obtain or are made aware of rel...,Operators that obtain or are made aware of rel...,[],[downstream operators and],[Addition],[nan],"[, Operators that obtain or are made aware of ...","[downstream operators and, Operators that obta...","[Addition, Equivalent, Equivalent]",2
24,Prior to placing relevant products on the mark...,Prior to placing relevant products on the mark...,[supplied by each particular supplier.],[],[Addition],[products],"[supplied by each particular supplier., Prior ...","[, Prior to placing relevant products on the m...","[Addition, Equivalent]",1
25,SME traders shall collect and keep the followi...,Downstream operators and traders shall collect...,"[SME, , ]","[Downstream operators and, place or, or export]","[Contradiction, Addition, Addition]","[nan, they intend to, they intend to]","[SME, , , traders shall collect and keep the f...","[Downstream operators and, place or, or export...","[Contradiction, Addition, Addition, Equivalent]",1
26,The annual payment for each farmer shall not e...,The annual payment for each farmer under parag...,"[, 1 250]","[under paragraph 1, 3 000]","[Addition, Contradiction]","[The annual payment, nan]","[, 1 250, The annual payment for each farmer]","[under paragraph 1, 3 000, The annual payment ...","[Addition, Contradiction, Equivalent]",1
27,The checks on SME traders shall include the ex...,The checks on downstream operators and traders...,[SME],[downstream operators and],[Contradiction],[nan],"[SME, traders shall include the examination of...","[downstream operators and, traders shall inclu...","[Contradiction, Equivalent, Equivalent]",2
28,The checks on SME traders shall include the ex...,The checks on downstream operators and traders...,[],"[(1),]",[Addition],[Article 5],"[, traders shall include the examination of do...","[(1),, traders shall include the examination o...","[Addition, Equivalent]",1
29,The checks on operators and non-SME traders sh...,The checks on operators shall include:,[and non-SME traders],[],[Addition],[The cheks on],[and non-SME traders],[],[Addition],0
30,The multiannual survey programmes shall be for...,The multiannual survey programmes shall be est...,"[, seven]","[established, 10]","[Addition, Contradiction]","[The multiannual survey programmes shall be, nan]","[, seven, The multiannual survey programmes sh...","[established, 10, The multiannual survey progr...","[Addition, Contradiction, Equivalent]",1
31,The scheme of authorisations for vine planting...,The scheme of authorisations for vine planting...,"[to 31 December 2045, two mid-term reviews, 2040]","[, a review, every ten years thereafter]","[Addition, Contradiction, Contradiction]","[nan, nan, nan]","[to 31 December 2045, two mid-term reviews, 20...","[, a review, every ten years thereafter, The s...","[Addition, Contradiction, Contradiction, Equiv...",3
32,The support shall take the form of a lump sum ...,The support shall take the form of a lump sum ...,"[30 June 2021, 31 December 2020]","[31 December 2021, 30 June 2021]","[Contradiction, Contradiction]","[nan, nan]","[30 June 2021, 31 December 2020, The support s...","[31 December 2021, 30 June 2021, The support s...","[Contradiction, Contradiction, Equivalent, Equ...",2
33,When applicable this table shall indicate sepa...,"When applicable, that table shall also indicat...",[],[also],[Addition],[table shall],"[, indicate separately within the total EAFRD ...","[also, indicate separately, within the total E...","[Addition, Equivalent, Equivalent, Equivalent]",3
34,investments in tangible and intangible assets ...,investments in tangible assets and intangible ...,"[, ]","[assets, including marketing through wine tour...","[Addition, Addition]","[investments in, marketing structures and tools]","[, , farming systems, excluding operations rel...","[assets, including marketing through wine tour...","[Addition, Addition, Equivalent]",1
35,"the Member State strategy, consisting of the f...","the Member State strategy, consisting of the t...",[financial products and their minimum],"[type of financing, the target]",[Contradiction],[nan],"[financial products and their minimum, the Mem...","[type of financing, the target, the Member Sta...","[Contradiction, Equivalent, Equivalent]",2
36,the performance reporting on output indicators...,the performance reporting on output indicators...,[for the purposes of the annual performance cl...,[],[Addition],[the performance reporting on output indicators],[for the purposes of the annual performance cl...,"[, the performance reporting on output indicat...","[Addition, Equivalent, Equivalent]",2
37,they are covered by a due diligence statement.,they are covered by a due diligence statement ...,[],"[or a simplified declaration, as required by t...",[Addition],[they are covered by],"[, they are covered by a due diligence statement]","[or a simplified declaration, as required by t...","[Addition, Equivalent]",1
38,"varietal conversions, also by means of graftin...","varietal conversions, also by means of graftin...","[the, ]","[, increasing the climate resilience of vines,]","[Addition, Addition]","[quality, for reasons of]","[the, , varietal conversions, also by means of...","[, increasing the climate resilience of vines,...","[Addition, Addition, Equivalent, Equivalent]",2
39,‘authorised representative’ means any natural ...,‘authorised representative’ means any natural ...,"[or from a trader, or the trader's]","[, ]","[Addition, Addition]","[a written mandate from an operator, the opera...","[or from a trader, or the trader's, authorised...","[, , authorised representative’ means any natu...","[Addition, Addition, Equivalent, Equivalent, E...",3
40,‘compartment’ means a part of the EU guarantee...,‘compartment’ means a part of the support prov...,[EU guarantee],[support provided under the InvestEU Fund],[Contradiction],[nan],"[EU guarantee, compartment’ means a part of th...","[support provided under the InvestEU Fund, com...","[Contradiction, Equivalent, Equivalent]",2
41,‘contribution agreement’ means a legal instrum...,‘contribution agreement’ means a legal instrum...,"[of the EU guarantee, ]","[for the implementation of the contribution, a...","[Contradiction, Addition]","[nan, Articles]","[of the EU guarantee, , contribution agreement...","[for the implementation of the contribution, a...","[Contradiction, Addition, Equivalent, Equivalent]",2
42,‘‘(1) the Committee on District of Columbia of...,‘‘(1) the Committee on District of Columbia of...,[Reform],[Accountability],[Contradiction],[nan],"[Reform, (1) the Committee on District of Colu...","[Accountability, (1) the Committee on District...","[Contradiction, Equivalent, Equivalent]",2
43,‘‘(3) Payment of expenses for the procurement ...,‘‘(3) Payment of expenses for the procurement ...,[President-elect or Vice-President-elect],[apparent successful candidate],[Contradiction],[nan],"[President-elect or Vice-President-elect, (3) ...","[apparent successful candidate, (3) Payment of...","[Contradiction, Equivalent, Equivalent]",2

In [31]:
output = result[['paragraph_1', 'paragraph_2', 'span_1_ext', 'span_2_ext', 'Label_ext']].explode(['span_1_ext', 'span_2_ext', 'Label_ext'])

In [29]:
!mkdir rulesm_raw

mkdir: cannot create directory ‘rulesm_raw’: File exists

In [32]:
output.to_csv('rulesm_raw/rulesm_en_with_equivalents.csv', index=False)

In [33]:
output.reset_index(drop=True)

,paragraph_1,paragraph_2,span_1_ext,span_2_ext,Label_ext
0,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,"3,237,000","10,000,000",Contradiction
1,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,Equivalent
2,(A) individual or individual and spouse engage...,(A) individual or individual and spouse engage...,and not less than 50 percent of whose aggregat...,and not less than 50 percent of whose aggregat...,Equivalent
3,"(A) subject to subparagraph (B), means a perso...","(A) subject to subparagraph (B), means a perso...",or operating real property or activities incid...,single asset real estate,Contradiction
4,"(A) subject to subparagraph (B), means a perso...","(A) subject to subparagraph (B), means a perso...",for a case in which the United States trustee has,,Addition
...,...,...,...,...,...
144,‘‘(1) the Committee on District of Columbia of...,‘‘(1) the Committee on District of Columbia of...,(1) the Committee on District of Columbia of t...,(1) the Committee on District of Columbia of t...,Equivalent
145,‘‘(1) the Committee on District of Columbia of...,‘‘(1) the Committee on District of Columbia of...,] of the House of Representatives,] of the House of Representatives,Equivalent
146,‘‘(3) Payment of expenses for the procurement ...,‘‘(3) Payment of expenses for the procurement ...,President-elect or Vice-President-elect,apparent successful candidate,Contradiction
147,‘‘(3) Payment of expenses for the procurement ...,‘‘(3) Payment of expenses for the procurement ...,(3) Payment of expenses for the procurement of...,(3) Payment of expenses for the procurement of...,Equivalent
148,‘‘(3) Payment of expenses for the procurement ...,‘‘(3) Payment of expenses for the procurement ...,as authorized for the head of any department b...,as authorized for the head of any department b...,Equivalent